export const type = {
    // Sync
    FILL_TASKS:              'FILL_TASKS',
    CREATE_TASK:             'CREATE_TASK',
    COMPLETE_TASK:           'COMPLETE_TASK',
    SORT_TASK:               'SORT_TASK',
    SORT_ORDER_TASK:         'SORT_ORDER_TASK',
    CHANGE_TASK:             'CHANGE_TASK',
    SHOW_MODAL_PREVIEW_TASK: 'SHOW_MODAL_PREVIEW_TASK',
    HIDE_MODAL_PREVIEW_TASK: 'HIDE_MODAL_PREVIEW_TASK',
    SHOW_MODAL_EDIT_TASK:    'SHOW_MODAL_EDIT_TASK',
    HIDE_MODAL_EDIT_TASK:    'HIDE_MODAL_EDIT_TASK',
    CHANGE_PAGE:             'CHANGE_PAGE',
    // Asyn
    FETCH_TASKS_ASYNC:       'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC:       'CREATE_TASK_ASYNC',
    COMPLETE_TASK_ASYNC:     'COMPLETE_TASK_ASYNC',
    CHANGE_TASK_ASYNC:       'CHANGE_TASK_ASYNC',
};
